namespace test_overloading
{
	struct Z
	{
	};
}
void* operator++			(test_overloading::Z&, int);
void* operator--			(test_overloading::Z&, int);
void* operator++			(test_overloading::Z&);
void* operator--			(test_overloading::Z&);
void* operator~				(test_overloading::Z&);
void* operator!				(test_overloading::Z&);
void* operator-				(test_overloading::Z&);
void* operator+				(test_overloading::Z&);
void* operator&				(test_overloading::Z&);
void* operator*				(test_overloading::Z&);
void* operator*				(test_overloading::Z&, int);
void* operator/				(test_overloading::Z&, int);
void* operator%				(test_overloading::Z&, int);
void* operator+				(test_overloading::Z&, int);
void* operator-				(test_overloading::Z&, int);
void* operator<<			(test_overloading::Z&, int);
void* operator>>			(test_overloading::Z&, int);
void* operator==			(test_overloading::Z&, int);
void* operator!=			(test_overloading::Z&, int);
void* operator<				(test_overloading::Z&, int);
void* operator<=			(test_overloading::Z&, int);
void* operator>				(test_overloading::Z&, int);
void* operator>=			(test_overloading::Z&, int);
void* operator&				(test_overloading::Z&, int);
void* operator|				(test_overloading::Z&, int);
void* operator^				(test_overloading::Z&, int);
void* operator&&			(test_overloading::Z&, int);
void* operator||			(test_overloading::Z&, int);
void* operator*=			(test_overloading::Z&, int);
void* operator/=			(test_overloading::Z&, int);
void* operator%=			(test_overloading::Z&, int);
void* operator+=			(test_overloading::Z&, int);
void* operator-=			(test_overloading::Z&, int);
void* operator<<=			(test_overloading::Z&, int);
void* operator>>=			(test_overloading::Z&, int);
void* operator&=			(test_overloading::Z&, int);
void* operator|=			(test_overloading::Z&, int);
void* operator^=			(test_overloading::Z&, int);
void* operator,				(test_overloading::Z&, int);
void* operator*				(int, test_overloading::Z&);
void* operator/				(int, test_overloading::Z&);
void* operator%				(int, test_overloading::Z&);
void* operator+				(int, test_overloading::Z&);
void* operator-				(int, test_overloading::Z&);
void* operator<<			(int, test_overloading::Z&);
void* operator>>			(int, test_overloading::Z&);
void* operator==			(int, test_overloading::Z&);
void* operator!=			(int, test_overloading::Z&);
void* operator<				(int, test_overloading::Z&);
void* operator<=			(int, test_overloading::Z&);
void* operator>				(int, test_overloading::Z&);
void* operator>=			(int, test_overloading::Z&);
void* operator&				(int, test_overloading::Z&);
void* operator|				(int, test_overloading::Z&);
void* operator^				(int, test_overloading::Z&);
void* operator&&			(int, test_overloading::Z&);
void* operator||			(int, test_overloading::Z&);
void* operator*=			(int, test_overloading::Z&);
void* operator/=			(int, test_overloading::Z&);
void* operator%=			(int, test_overloading::Z&);
void* operator+=			(int, test_overloading::Z&);
void* operator-=			(int, test_overloading::Z&);
void* operator<<=			(int, test_overloading::Z&);
void* operator>>=			(int, test_overloading::Z&);
void* operator&=			(int, test_overloading::Z&);
void* operator|=			(int, test_overloading::Z&);
void* operator^=			(int, test_overloading::Z&);
void* operator,				(int, test_overloading::Z&);

bool* operator++			(const test_overloading::Z&, int);
bool* operator--			(const test_overloading::Z&, int);
bool* operator++			(const test_overloading::Z&);
bool* operator--			(const test_overloading::Z&);
bool* operator~				(const test_overloading::Z&);
bool* operator!				(const test_overloading::Z&);
bool* operator-				(const test_overloading::Z&);
bool* operator+				(const test_overloading::Z&);
bool* operator&				(const test_overloading::Z&);
bool* operator*				(const test_overloading::Z&);
bool* operator*				(const test_overloading::Z&, int);
bool* operator/				(const test_overloading::Z&, int);
bool* operator%				(const test_overloading::Z&, int);
bool* operator+				(const test_overloading::Z&, int);
bool* operator-				(const test_overloading::Z&, int);
bool* operator<<			(const test_overloading::Z&, int);
bool* operator>>			(const test_overloading::Z&, int);
bool* operator==			(const test_overloading::Z&, int);
bool* operator!=			(const test_overloading::Z&, int);
bool* operator<				(const test_overloading::Z&, int);
bool* operator<=			(const test_overloading::Z&, int);
bool* operator>				(const test_overloading::Z&, int);
bool* operator>=			(const test_overloading::Z&, int);
bool* operator&				(const test_overloading::Z&, int);
bool* operator|				(const test_overloading::Z&, int);
bool* operator^				(const test_overloading::Z&, int);
bool* operator&&			(const test_overloading::Z&, int);
bool* operator||			(const test_overloading::Z&, int);
bool* operator*=			(const test_overloading::Z&, int);
bool* operator/=			(const test_overloading::Z&, int);
bool* operator%=			(const test_overloading::Z&, int);
bool* operator+=			(const test_overloading::Z&, int);
bool* operator-=			(const test_overloading::Z&, int);
bool* operator<<=			(const test_overloading::Z&, int);
bool* operator>>=			(const test_overloading::Z&, int);
bool* operator&=			(const test_overloading::Z&, int);
bool* operator|=			(const test_overloading::Z&, int);
bool* operator^=			(const test_overloading::Z&, int);
bool* operator,				(const test_overloading::Z&, int);
bool* operator*				(int, const test_overloading::Z&);
bool* operator/				(int, const test_overloading::Z&);
bool* operator%				(int, const test_overloading::Z&);
bool* operator+				(int, const test_overloading::Z&);
bool* operator-				(int, const test_overloading::Z&);
bool* operator<<			(int, const test_overloading::Z&);
bool* operator>>			(int, const test_overloading::Z&);
bool* operator==			(int, const test_overloading::Z&);
bool* operator!=			(int, const test_overloading::Z&);
bool* operator<				(int, const test_overloading::Z&);
bool* operator<=			(int, const test_overloading::Z&);
bool* operator>				(int, const test_overloading::Z&);
bool* operator>=			(int, const test_overloading::Z&);
bool* operator&				(int, const test_overloading::Z&);
bool* operator|				(int, const test_overloading::Z&);
bool* operator^				(int, const test_overloading::Z&);
bool* operator&&			(int, const test_overloading::Z&);
bool* operator||			(int, const test_overloading::Z&);
bool* operator*=			(int, const test_overloading::Z&);
bool* operator/=			(int, const test_overloading::Z&);
bool* operator%=			(int, const test_overloading::Z&);
bool* operator+=			(int, const test_overloading::Z&);
bool* operator-=			(int, const test_overloading::Z&);
bool* operator<<=			(int, const test_overloading::Z&);
bool* operator>>=			(int, const test_overloading::Z&);
bool* operator&=			(int, const test_overloading::Z&);
bool* operator|=			(int, const test_overloading::Z&);
bool* operator^=			(int, const test_overloading::Z&);
bool* operator,				(int, const test_overloading::Z&);
