#define GENERATED_FUNCTION_TYPES(F)\
	F(oDC_oCC_oMC_oCA_oMA_oDD_)\
	F(nDC_oCC_oMC_oCA_oMA_oDD_)\
	F(xDC_oCC_oMC_oCA_oMA_oDD_)\
	F(oDC_nCC_oMC_oCA_oMA_oDD_)\
	F(nDC_nCC_oMC_oCA_oMA_oDD_)\
	F(xDC_nCC_oMC_oCA_oMA_oDD_)\
	F(oDC_xCC_oMC_oCA_oMA_oDD_)\
	F(nDC_xCC_oMC_oCA_oMA_oDD_)\
	F(xDC_xCC_oMC_oCA_oMA_oDD_)\
	F(oDC_oCC_nMC_oCA_oMA_oDD_)\
	F(nDC_oCC_nMC_oCA_oMA_oDD_)\
	F(xDC_oCC_nMC_oCA_oMA_oDD_)\
	F(oDC_nCC_nMC_oCA_oMA_oDD_)\
	F(nDC_nCC_nMC_oCA_oMA_oDD_)\
	F(xDC_nCC_nMC_oCA_oMA_oDD_)\
	F(oDC_xCC_nMC_oCA_oMA_oDD_)\
	F(nDC_xCC_nMC_oCA_oMA_oDD_)\
	F(xDC_xCC_nMC_oCA_oMA_oDD_)\
	F(oDC_oCC_xMC_oCA_oMA_oDD_)\
	F(nDC_oCC_xMC_oCA_oMA_oDD_)\
	F(xDC_oCC_xMC_oCA_oMA_oDD_)\
	F(oDC_nCC_xMC_oCA_oMA_oDD_)\
	F(nDC_nCC_xMC_oCA_oMA_oDD_)\
	F(xDC_nCC_xMC_oCA_oMA_oDD_)\
	F(oDC_xCC_xMC_oCA_oMA_oDD_)\
	F(nDC_xCC_xMC_oCA_oMA_oDD_)\
	F(xDC_xCC_xMC_oCA_oMA_oDD_)\
	F(oDC_oCC_oMC_nCA_oMA_oDD_)\
	F(nDC_oCC_oMC_nCA_oMA_oDD_)\
	F(xDC_oCC_oMC_nCA_oMA_oDD_)\
	F(oDC_nCC_oMC_nCA_oMA_oDD_)\
	F(nDC_nCC_oMC_nCA_oMA_oDD_)\
	F(xDC_nCC_oMC_nCA_oMA_oDD_)\
	F(oDC_xCC_oMC_nCA_oMA_oDD_)\
	F(nDC_xCC_oMC_nCA_oMA_oDD_)\
	F(xDC_xCC_oMC_nCA_oMA_oDD_)\
	F(oDC_oCC_nMC_nCA_oMA_oDD_)\
	F(nDC_oCC_nMC_nCA_oMA_oDD_)\
	F(xDC_oCC_nMC_nCA_oMA_oDD_)\
	F(oDC_nCC_nMC_nCA_oMA_oDD_)\
	F(nDC_nCC_nMC_nCA_oMA_oDD_)\
	F(xDC_nCC_nMC_nCA_oMA_oDD_)\
	F(oDC_xCC_nMC_nCA_oMA_oDD_)\
	F(nDC_xCC_nMC_nCA_oMA_oDD_)\
	F(xDC_xCC_nMC_nCA_oMA_oDD_)\
	F(oDC_oCC_xMC_nCA_oMA_oDD_)\
	F(nDC_oCC_xMC_nCA_oMA_oDD_)\
	F(xDC_oCC_xMC_nCA_oMA_oDD_)\
	F(oDC_nCC_xMC_nCA_oMA_oDD_)\
	F(nDC_nCC_xMC_nCA_oMA_oDD_)\
	F(xDC_nCC_xMC_nCA_oMA_oDD_)\
	F(oDC_xCC_xMC_nCA_oMA_oDD_)\
	F(nDC_xCC_xMC_nCA_oMA_oDD_)\
	F(xDC_xCC_xMC_nCA_oMA_oDD_)\
	F(oDC_oCC_oMC_xCA_oMA_oDD_)\
	F(nDC_oCC_oMC_xCA_oMA_oDD_)\
	F(xDC_oCC_oMC_xCA_oMA_oDD_)\
	F(oDC_nCC_oMC_xCA_oMA_oDD_)\
	F(nDC_nCC_oMC_xCA_oMA_oDD_)\
	F(xDC_nCC_oMC_xCA_oMA_oDD_)\
	F(oDC_xCC_oMC_xCA_oMA_oDD_)\
	F(nDC_xCC_oMC_xCA_oMA_oDD_)\
	F(xDC_xCC_oMC_xCA_oMA_oDD_)\
	F(oDC_oCC_nMC_xCA_oMA_oDD_)\
	F(nDC_oCC_nMC_xCA_oMA_oDD_)\
	F(xDC_oCC_nMC_xCA_oMA_oDD_)\
	F(oDC_nCC_nMC_xCA_oMA_oDD_)\
	F(nDC_nCC_nMC_xCA_oMA_oDD_)\
	F(xDC_nCC_nMC_xCA_oMA_oDD_)\
	F(oDC_xCC_nMC_xCA_oMA_oDD_)\
	F(nDC_xCC_nMC_xCA_oMA_oDD_)\
	F(xDC_xCC_nMC_xCA_oMA_oDD_)\
	F(oDC_oCC_xMC_xCA_oMA_oDD_)\
	F(nDC_oCC_xMC_xCA_oMA_oDD_)\
	F(xDC_oCC_xMC_xCA_oMA_oDD_)\
	F(oDC_nCC_xMC_xCA_oMA_oDD_)\
	F(nDC_nCC_xMC_xCA_oMA_oDD_)\
	F(xDC_nCC_xMC_xCA_oMA_oDD_)\
	F(oDC_xCC_xMC_xCA_oMA_oDD_)\
	F(nDC_xCC_xMC_xCA_oMA_oDD_)\
	F(xDC_xCC_xMC_xCA_oMA_oDD_)\
	F(oDC_oCC_oMC_oCA_nMA_oDD_)\
	F(nDC_oCC_oMC_oCA_nMA_oDD_)\
	F(xDC_oCC_oMC_oCA_nMA_oDD_)\
	F(oDC_nCC_oMC_oCA_nMA_oDD_)\
	F(nDC_nCC_oMC_oCA_nMA_oDD_)\
	F(xDC_nCC_oMC_oCA_nMA_oDD_)\
	F(oDC_xCC_oMC_oCA_nMA_oDD_)\
	F(nDC_xCC_oMC_oCA_nMA_oDD_)\
	F(xDC_xCC_oMC_oCA_nMA_oDD_)\
	F(oDC_oCC_nMC_oCA_nMA_oDD_)\
	F(nDC_oCC_nMC_oCA_nMA_oDD_)\
	F(xDC_oCC_nMC_oCA_nMA_oDD_)\
	F(oDC_nCC_nMC_oCA_nMA_oDD_)\
	F(nDC_nCC_nMC_oCA_nMA_oDD_)\
	F(xDC_nCC_nMC_oCA_nMA_oDD_)\
	F(oDC_xCC_nMC_oCA_nMA_oDD_)\
	F(nDC_xCC_nMC_oCA_nMA_oDD_)\
	F(xDC_xCC_nMC_oCA_nMA_oDD_)\
	F(oDC_oCC_xMC_oCA_nMA_oDD_)\
	F(nDC_oCC_xMC_oCA_nMA_oDD_)\
	F(xDC_oCC_xMC_oCA_nMA_oDD_)\
	F(oDC_nCC_xMC_oCA_nMA_oDD_)\
	F(nDC_nCC_xMC_oCA_nMA_oDD_)\
	F(xDC_nCC_xMC_oCA_nMA_oDD_)\
	F(oDC_xCC_xMC_oCA_nMA_oDD_)\
	F(nDC_xCC_xMC_oCA_nMA_oDD_)\
	F(xDC_xCC_xMC_oCA_nMA_oDD_)\
	F(oDC_oCC_oMC_nCA_nMA_oDD_)\
	F(nDC_oCC_oMC_nCA_nMA_oDD_)\
	F(xDC_oCC_oMC_nCA_nMA_oDD_)\
	F(oDC_nCC_oMC_nCA_nMA_oDD_)\
	F(nDC_nCC_oMC_nCA_nMA_oDD_)\
	F(xDC_nCC_oMC_nCA_nMA_oDD_)\
	F(oDC_xCC_oMC_nCA_nMA_oDD_)\
	F(nDC_xCC_oMC_nCA_nMA_oDD_)\
	F(xDC_xCC_oMC_nCA_nMA_oDD_)\
	F(oDC_oCC_nMC_nCA_nMA_oDD_)\
	F(nDC_oCC_nMC_nCA_nMA_oDD_)\
	F(xDC_oCC_nMC_nCA_nMA_oDD_)\
	F(oDC_nCC_nMC_nCA_nMA_oDD_)\
	F(nDC_nCC_nMC_nCA_nMA_oDD_)\
	F(xDC_nCC_nMC_nCA_nMA_oDD_)\
	F(oDC_xCC_nMC_nCA_nMA_oDD_)\
	F(nDC_xCC_nMC_nCA_nMA_oDD_)\
	F(xDC_xCC_nMC_nCA_nMA_oDD_)\
	F(oDC_oCC_xMC_nCA_nMA_oDD_)\
	F(nDC_oCC_xMC_nCA_nMA_oDD_)\
	F(xDC_oCC_xMC_nCA_nMA_oDD_)\
	F(oDC_nCC_xMC_nCA_nMA_oDD_)\
	F(nDC_nCC_xMC_nCA_nMA_oDD_)\
	F(xDC_nCC_xMC_nCA_nMA_oDD_)\
	F(oDC_xCC_xMC_nCA_nMA_oDD_)\
	F(nDC_xCC_xMC_nCA_nMA_oDD_)\
	F(xDC_xCC_xMC_nCA_nMA_oDD_)\
	F(oDC_oCC_oMC_xCA_nMA_oDD_)\
	F(nDC_oCC_oMC_xCA_nMA_oDD_)\
	F(xDC_oCC_oMC_xCA_nMA_oDD_)\
	F(oDC_nCC_oMC_xCA_nMA_oDD_)\
	F(nDC_nCC_oMC_xCA_nMA_oDD_)\
	F(xDC_nCC_oMC_xCA_nMA_oDD_)\
	F(oDC_xCC_oMC_xCA_nMA_oDD_)\
	F(nDC_xCC_oMC_xCA_nMA_oDD_)\
	F(xDC_xCC_oMC_xCA_nMA_oDD_)\
	F(oDC_oCC_nMC_xCA_nMA_oDD_)\
	F(nDC_oCC_nMC_xCA_nMA_oDD_)\
	F(xDC_oCC_nMC_xCA_nMA_oDD_)\
	F(oDC_nCC_nMC_xCA_nMA_oDD_)\
	F(nDC_nCC_nMC_xCA_nMA_oDD_)\
	F(xDC_nCC_nMC_xCA_nMA_oDD_)\
	F(oDC_xCC_nMC_xCA_nMA_oDD_)\
	F(nDC_xCC_nMC_xCA_nMA_oDD_)\
	F(xDC_xCC_nMC_xCA_nMA_oDD_)\
	F(oDC_oCC_xMC_xCA_nMA_oDD_)\
	F(nDC_oCC_xMC_xCA_nMA_oDD_)\
	F(xDC_oCC_xMC_xCA_nMA_oDD_)\
	F(oDC_nCC_xMC_xCA_nMA_oDD_)\
	F(nDC_nCC_xMC_xCA_nMA_oDD_)\
	F(xDC_nCC_xMC_xCA_nMA_oDD_)\
	F(oDC_xCC_xMC_xCA_nMA_oDD_)\
	F(nDC_xCC_xMC_xCA_nMA_oDD_)\
	F(xDC_xCC_xMC_xCA_nMA_oDD_)\
	F(oDC_oCC_oMC_oCA_xMA_oDD_)\
	F(nDC_oCC_oMC_oCA_xMA_oDD_)\
	F(xDC_oCC_oMC_oCA_xMA_oDD_)\
	F(oDC_nCC_oMC_oCA_xMA_oDD_)\
	F(nDC_nCC_oMC_oCA_xMA_oDD_)\
	F(xDC_nCC_oMC_oCA_xMA_oDD_)\
	F(oDC_xCC_oMC_oCA_xMA_oDD_)\
	F(nDC_xCC_oMC_oCA_xMA_oDD_)\
	F(xDC_xCC_oMC_oCA_xMA_oDD_)\
	F(oDC_oCC_nMC_oCA_xMA_oDD_)\
	F(nDC_oCC_nMC_oCA_xMA_oDD_)\
	F(xDC_oCC_nMC_oCA_xMA_oDD_)\
	F(oDC_nCC_nMC_oCA_xMA_oDD_)\
	F(nDC_nCC_nMC_oCA_xMA_oDD_)\
	F(xDC_nCC_nMC_oCA_xMA_oDD_)\
	F(oDC_xCC_nMC_oCA_xMA_oDD_)\
	F(nDC_xCC_nMC_oCA_xMA_oDD_)\
	F(xDC_xCC_nMC_oCA_xMA_oDD_)\
	F(oDC_oCC_xMC_oCA_xMA_oDD_)\
	F(nDC_oCC_xMC_oCA_xMA_oDD_)\
	F(xDC_oCC_xMC_oCA_xMA_oDD_)\
	F(oDC_nCC_xMC_oCA_xMA_oDD_)\
	F(nDC_nCC_xMC_oCA_xMA_oDD_)\
	F(xDC_nCC_xMC_oCA_xMA_oDD_)\
	F(oDC_xCC_xMC_oCA_xMA_oDD_)\
	F(nDC_xCC_xMC_oCA_xMA_oDD_)\
	F(xDC_xCC_xMC_oCA_xMA_oDD_)\
	F(oDC_oCC_oMC_nCA_xMA_oDD_)\
	F(nDC_oCC_oMC_nCA_xMA_oDD_)\
	F(xDC_oCC_oMC_nCA_xMA_oDD_)\
	F(oDC_nCC_oMC_nCA_xMA_oDD_)\
	F(nDC_nCC_oMC_nCA_xMA_oDD_)\
	F(xDC_nCC_oMC_nCA_xMA_oDD_)\
	F(oDC_xCC_oMC_nCA_xMA_oDD_)\
	F(nDC_xCC_oMC_nCA_xMA_oDD_)\
	F(xDC_xCC_oMC_nCA_xMA_oDD_)\
	F(oDC_oCC_nMC_nCA_xMA_oDD_)\
	F(nDC_oCC_nMC_nCA_xMA_oDD_)\
	F(xDC_oCC_nMC_nCA_xMA_oDD_)\
	F(oDC_nCC_nMC_nCA_xMA_oDD_)\
	F(nDC_nCC_nMC_nCA_xMA_oDD_)\
	F(xDC_nCC_nMC_nCA_xMA_oDD_)\
	F(oDC_xCC_nMC_nCA_xMA_oDD_)\
	F(nDC_xCC_nMC_nCA_xMA_oDD_)\
	F(xDC_xCC_nMC_nCA_xMA_oDD_)\
	F(oDC_oCC_xMC_nCA_xMA_oDD_)\
	F(nDC_oCC_xMC_nCA_xMA_oDD_)\
	F(xDC_oCC_xMC_nCA_xMA_oDD_)\
	F(oDC_nCC_xMC_nCA_xMA_oDD_)\
	F(nDC_nCC_xMC_nCA_xMA_oDD_)\
	F(xDC_nCC_xMC_nCA_xMA_oDD_)\
	F(oDC_xCC_xMC_nCA_xMA_oDD_)\
	F(nDC_xCC_xMC_nCA_xMA_oDD_)\
	F(xDC_xCC_xMC_nCA_xMA_oDD_)\
	F(oDC_oCC_oMC_xCA_xMA_oDD_)\
	F(nDC_oCC_oMC_xCA_xMA_oDD_)\
	F(xDC_oCC_oMC_xCA_xMA_oDD_)\
	F(oDC_nCC_oMC_xCA_xMA_oDD_)\
	F(nDC_nCC_oMC_xCA_xMA_oDD_)\
	F(xDC_nCC_oMC_xCA_xMA_oDD_)\
	F(oDC_xCC_oMC_xCA_xMA_oDD_)\
	F(nDC_xCC_oMC_xCA_xMA_oDD_)\
	F(xDC_xCC_oMC_xCA_xMA_oDD_)\
	F(oDC_oCC_nMC_xCA_xMA_oDD_)\
	F(nDC_oCC_nMC_xCA_xMA_oDD_)\
	F(xDC_oCC_nMC_xCA_xMA_oDD_)\
	F(oDC_nCC_nMC_xCA_xMA_oDD_)\
	F(nDC_nCC_nMC_xCA_xMA_oDD_)\
	F(xDC_nCC_nMC_xCA_xMA_oDD_)\
	F(oDC_xCC_nMC_xCA_xMA_oDD_)\
	F(nDC_xCC_nMC_xCA_xMA_oDD_)\
	F(xDC_xCC_nMC_xCA_xMA_oDD_)\
	F(oDC_oCC_xMC_xCA_xMA_oDD_)\
	F(nDC_oCC_xMC_xCA_xMA_oDD_)\
	F(xDC_oCC_xMC_xCA_xMA_oDD_)\
	F(oDC_nCC_xMC_xCA_xMA_oDD_)\
	F(nDC_nCC_xMC_xCA_xMA_oDD_)\
	F(xDC_nCC_xMC_xCA_xMA_oDD_)\
	F(oDC_xCC_xMC_xCA_xMA_oDD_)\
	F(nDC_xCC_xMC_xCA_xMA_oDD_)\
	F(xDC_xCC_xMC_xCA_xMA_oDD_)\
	F(oDC_oCC_oMC_oCA_oMA_nDD_)\
	F(nDC_oCC_oMC_oCA_oMA_nDD_)\
	F(xDC_oCC_oMC_oCA_oMA_nDD_)\
	F(oDC_nCC_oMC_oCA_oMA_nDD_)\
	F(nDC_nCC_oMC_oCA_oMA_nDD_)\
	F(xDC_nCC_oMC_oCA_oMA_nDD_)\
	F(oDC_xCC_oMC_oCA_oMA_nDD_)\
	F(nDC_xCC_oMC_oCA_oMA_nDD_)\
	F(xDC_xCC_oMC_oCA_oMA_nDD_)\
	F(oDC_oCC_nMC_oCA_oMA_nDD_)\
	F(nDC_oCC_nMC_oCA_oMA_nDD_)\
	F(xDC_oCC_nMC_oCA_oMA_nDD_)\
	F(oDC_nCC_nMC_oCA_oMA_nDD_)\
	F(nDC_nCC_nMC_oCA_oMA_nDD_)\
	F(xDC_nCC_nMC_oCA_oMA_nDD_)\
	F(oDC_xCC_nMC_oCA_oMA_nDD_)\
	F(nDC_xCC_nMC_oCA_oMA_nDD_)\
	F(xDC_xCC_nMC_oCA_oMA_nDD_)\
	F(oDC_oCC_xMC_oCA_oMA_nDD_)\
	F(nDC_oCC_xMC_oCA_oMA_nDD_)\
	F(xDC_oCC_xMC_oCA_oMA_nDD_)\
	F(oDC_nCC_xMC_oCA_oMA_nDD_)\
	F(nDC_nCC_xMC_oCA_oMA_nDD_)\
	F(xDC_nCC_xMC_oCA_oMA_nDD_)\
	F(oDC_xCC_xMC_oCA_oMA_nDD_)\
	F(nDC_xCC_xMC_oCA_oMA_nDD_)\
	F(xDC_xCC_xMC_oCA_oMA_nDD_)\
	F(oDC_oCC_oMC_nCA_oMA_nDD_)\
	F(nDC_oCC_oMC_nCA_oMA_nDD_)\
	F(xDC_oCC_oMC_nCA_oMA_nDD_)\
	F(oDC_nCC_oMC_nCA_oMA_nDD_)\
	F(nDC_nCC_oMC_nCA_oMA_nDD_)\
	F(xDC_nCC_oMC_nCA_oMA_nDD_)\
	F(oDC_xCC_oMC_nCA_oMA_nDD_)\
	F(nDC_xCC_oMC_nCA_oMA_nDD_)\
	F(xDC_xCC_oMC_nCA_oMA_nDD_)\
	F(oDC_oCC_nMC_nCA_oMA_nDD_)\
	F(nDC_oCC_nMC_nCA_oMA_nDD_)\
	F(xDC_oCC_nMC_nCA_oMA_nDD_)\
	F(oDC_nCC_nMC_nCA_oMA_nDD_)\
	F(nDC_nCC_nMC_nCA_oMA_nDD_)\
	F(xDC_nCC_nMC_nCA_oMA_nDD_)\
	F(oDC_xCC_nMC_nCA_oMA_nDD_)\
	F(nDC_xCC_nMC_nCA_oMA_nDD_)\
	F(xDC_xCC_nMC_nCA_oMA_nDD_)\
	F(oDC_oCC_xMC_nCA_oMA_nDD_)\
	F(nDC_oCC_xMC_nCA_oMA_nDD_)\
	F(xDC_oCC_xMC_nCA_oMA_nDD_)\
	F(oDC_nCC_xMC_nCA_oMA_nDD_)\
	F(nDC_nCC_xMC_nCA_oMA_nDD_)\
	F(xDC_nCC_xMC_nCA_oMA_nDD_)\
	F(oDC_xCC_xMC_nCA_oMA_nDD_)\
	F(nDC_xCC_xMC_nCA_oMA_nDD_)\
	F(xDC_xCC_xMC_nCA_oMA_nDD_)\
	F(oDC_oCC_oMC_xCA_oMA_nDD_)\
	F(nDC_oCC_oMC_xCA_oMA_nDD_)\
	F(xDC_oCC_oMC_xCA_oMA_nDD_)\
	F(oDC_nCC_oMC_xCA_oMA_nDD_)\
	F(nDC_nCC_oMC_xCA_oMA_nDD_)\
	F(xDC_nCC_oMC_xCA_oMA_nDD_)\
	F(oDC_xCC_oMC_xCA_oMA_nDD_)\
	F(nDC_xCC_oMC_xCA_oMA_nDD_)\
	F(xDC_xCC_oMC_xCA_oMA_nDD_)\
	F(oDC_oCC_nMC_xCA_oMA_nDD_)\
	F(nDC_oCC_nMC_xCA_oMA_nDD_)\
	F(xDC_oCC_nMC_xCA_oMA_nDD_)\
	F(oDC_nCC_nMC_xCA_oMA_nDD_)\
	F(nDC_nCC_nMC_xCA_oMA_nDD_)\
	F(xDC_nCC_nMC_xCA_oMA_nDD_)\
	F(oDC_xCC_nMC_xCA_oMA_nDD_)\
	F(nDC_xCC_nMC_xCA_oMA_nDD_)\
	F(xDC_xCC_nMC_xCA_oMA_nDD_)\
	F(oDC_oCC_xMC_xCA_oMA_nDD_)\
	F(nDC_oCC_xMC_xCA_oMA_nDD_)\
	F(xDC_oCC_xMC_xCA_oMA_nDD_)\
	F(oDC_nCC_xMC_xCA_oMA_nDD_)\
	F(nDC_nCC_xMC_xCA_oMA_nDD_)\
	F(xDC_nCC_xMC_xCA_oMA_nDD_)\
	F(oDC_xCC_xMC_xCA_oMA_nDD_)\
	F(nDC_xCC_xMC_xCA_oMA_nDD_)\
	F(xDC_xCC_xMC_xCA_oMA_nDD_)\
	F(oDC_oCC_oMC_oCA_nMA_nDD_)\
	F(nDC_oCC_oMC_oCA_nMA_nDD_)\
	F(xDC_oCC_oMC_oCA_nMA_nDD_)\
	F(oDC_nCC_oMC_oCA_nMA_nDD_)\
	F(nDC_nCC_oMC_oCA_nMA_nDD_)\
	F(xDC_nCC_oMC_oCA_nMA_nDD_)\
	F(oDC_xCC_oMC_oCA_nMA_nDD_)\
	F(nDC_xCC_oMC_oCA_nMA_nDD_)\
	F(xDC_xCC_oMC_oCA_nMA_nDD_)\
	F(oDC_oCC_nMC_oCA_nMA_nDD_)\
	F(nDC_oCC_nMC_oCA_nMA_nDD_)\
	F(xDC_oCC_nMC_oCA_nMA_nDD_)\
	F(oDC_nCC_nMC_oCA_nMA_nDD_)\
	F(nDC_nCC_nMC_oCA_nMA_nDD_)\
	F(xDC_nCC_nMC_oCA_nMA_nDD_)\
	F(oDC_xCC_nMC_oCA_nMA_nDD_)\
	F(nDC_xCC_nMC_oCA_nMA_nDD_)\
	F(xDC_xCC_nMC_oCA_nMA_nDD_)\
	F(oDC_oCC_xMC_oCA_nMA_nDD_)\
	F(nDC_oCC_xMC_oCA_nMA_nDD_)\
	F(xDC_oCC_xMC_oCA_nMA_nDD_)\
	F(oDC_nCC_xMC_oCA_nMA_nDD_)\
	F(nDC_nCC_xMC_oCA_nMA_nDD_)\
	F(xDC_nCC_xMC_oCA_nMA_nDD_)\
	F(oDC_xCC_xMC_oCA_nMA_nDD_)\
	F(nDC_xCC_xMC_oCA_nMA_nDD_)\
	F(xDC_xCC_xMC_oCA_nMA_nDD_)\
	F(oDC_oCC_oMC_nCA_nMA_nDD_)\
	F(nDC_oCC_oMC_nCA_nMA_nDD_)\
	F(xDC_oCC_oMC_nCA_nMA_nDD_)\
	F(oDC_nCC_oMC_nCA_nMA_nDD_)\
	F(nDC_nCC_oMC_nCA_nMA_nDD_)\
	F(xDC_nCC_oMC_nCA_nMA_nDD_)\
	F(oDC_xCC_oMC_nCA_nMA_nDD_)\
	F(nDC_xCC_oMC_nCA_nMA_nDD_)\
	F(xDC_xCC_oMC_nCA_nMA_nDD_)\
	F(oDC_oCC_nMC_nCA_nMA_nDD_)\
	F(nDC_oCC_nMC_nCA_nMA_nDD_)\
	F(xDC_oCC_nMC_nCA_nMA_nDD_)\
	F(oDC_nCC_nMC_nCA_nMA_nDD_)\
	F(nDC_nCC_nMC_nCA_nMA_nDD_)\
	F(xDC_nCC_nMC_nCA_nMA_nDD_)\
	F(oDC_xCC_nMC_nCA_nMA_nDD_)\
	F(nDC_xCC_nMC_nCA_nMA_nDD_)\
	F(xDC_xCC_nMC_nCA_nMA_nDD_)\
	F(oDC_oCC_xMC_nCA_nMA_nDD_)\
	F(nDC_oCC_xMC_nCA_nMA_nDD_)\
	F(xDC_oCC_xMC_nCA_nMA_nDD_)\
	F(oDC_nCC_xMC_nCA_nMA_nDD_)\
	F(nDC_nCC_xMC_nCA_nMA_nDD_)\
	F(xDC_nCC_xMC_nCA_nMA_nDD_)\
	F(oDC_xCC_xMC_nCA_nMA_nDD_)\
	F(nDC_xCC_xMC_nCA_nMA_nDD_)\
	F(xDC_xCC_xMC_nCA_nMA_nDD_)\
	F(oDC_oCC_oMC_xCA_nMA_nDD_)\
	F(nDC_oCC_oMC_xCA_nMA_nDD_)\
	F(xDC_oCC_oMC_xCA_nMA_nDD_)\
	F(oDC_nCC_oMC_xCA_nMA_nDD_)\
	F(nDC_nCC_oMC_xCA_nMA_nDD_)\
	F(xDC_nCC_oMC_xCA_nMA_nDD_)\
	F(oDC_xCC_oMC_xCA_nMA_nDD_)\
	F(nDC_xCC_oMC_xCA_nMA_nDD_)\
	F(xDC_xCC_oMC_xCA_nMA_nDD_)\
	F(oDC_oCC_nMC_xCA_nMA_nDD_)\
	F(nDC_oCC_nMC_xCA_nMA_nDD_)\
	F(xDC_oCC_nMC_xCA_nMA_nDD_)\
	F(oDC_nCC_nMC_xCA_nMA_nDD_)\
	F(nDC_nCC_nMC_xCA_nMA_nDD_)\
	F(xDC_nCC_nMC_xCA_nMA_nDD_)\
	F(oDC_xCC_nMC_xCA_nMA_nDD_)\
	F(nDC_xCC_nMC_xCA_nMA_nDD_)\
	F(xDC_xCC_nMC_xCA_nMA_nDD_)\
	F(oDC_oCC_xMC_xCA_nMA_nDD_)\
	F(nDC_oCC_xMC_xCA_nMA_nDD_)\
	F(xDC_oCC_xMC_xCA_nMA_nDD_)\
	F(oDC_nCC_xMC_xCA_nMA_nDD_)\
	F(nDC_nCC_xMC_xCA_nMA_nDD_)\
	F(xDC_nCC_xMC_xCA_nMA_nDD_)\
	F(oDC_xCC_xMC_xCA_nMA_nDD_)\
	F(nDC_xCC_xMC_xCA_nMA_nDD_)\
	F(xDC_xCC_xMC_xCA_nMA_nDD_)\
	F(oDC_oCC_oMC_oCA_xMA_nDD_)\
	F(nDC_oCC_oMC_oCA_xMA_nDD_)\
	F(xDC_oCC_oMC_oCA_xMA_nDD_)\
	F(oDC_nCC_oMC_oCA_xMA_nDD_)\
	F(nDC_nCC_oMC_oCA_xMA_nDD_)\
	F(xDC_nCC_oMC_oCA_xMA_nDD_)\
	F(oDC_xCC_oMC_oCA_xMA_nDD_)\
	F(nDC_xCC_oMC_oCA_xMA_nDD_)\
	F(xDC_xCC_oMC_oCA_xMA_nDD_)\
	F(oDC_oCC_nMC_oCA_xMA_nDD_)\
	F(nDC_oCC_nMC_oCA_xMA_nDD_)\
	F(xDC_oCC_nMC_oCA_xMA_nDD_)\
	F(oDC_nCC_nMC_oCA_xMA_nDD_)\
	F(nDC_nCC_nMC_oCA_xMA_nDD_)\
	F(xDC_nCC_nMC_oCA_xMA_nDD_)\
	F(oDC_xCC_nMC_oCA_xMA_nDD_)\
	F(nDC_xCC_nMC_oCA_xMA_nDD_)\
	F(xDC_xCC_nMC_oCA_xMA_nDD_)\
	F(oDC_oCC_xMC_oCA_xMA_nDD_)\
	F(nDC_oCC_xMC_oCA_xMA_nDD_)\
	F(xDC_oCC_xMC_oCA_xMA_nDD_)\
	F(oDC_nCC_xMC_oCA_xMA_nDD_)\
	F(nDC_nCC_xMC_oCA_xMA_nDD_)\
	F(xDC_nCC_xMC_oCA_xMA_nDD_)\
	F(oDC_xCC_xMC_oCA_xMA_nDD_)\
	F(nDC_xCC_xMC_oCA_xMA_nDD_)\
	F(xDC_xCC_xMC_oCA_xMA_nDD_)\
	F(oDC_oCC_oMC_nCA_xMA_nDD_)\
	F(nDC_oCC_oMC_nCA_xMA_nDD_)\
	F(xDC_oCC_oMC_nCA_xMA_nDD_)\
	F(oDC_nCC_oMC_nCA_xMA_nDD_)\
	F(nDC_nCC_oMC_nCA_xMA_nDD_)\
	F(xDC_nCC_oMC_nCA_xMA_nDD_)\
	F(oDC_xCC_oMC_nCA_xMA_nDD_)\
	F(nDC_xCC_oMC_nCA_xMA_nDD_)\
	F(xDC_xCC_oMC_nCA_xMA_nDD_)\
	F(oDC_oCC_nMC_nCA_xMA_nDD_)\
	F(nDC_oCC_nMC_nCA_xMA_nDD_)\
	F(xDC_oCC_nMC_nCA_xMA_nDD_)\
	F(oDC_nCC_nMC_nCA_xMA_nDD_)\
	F(nDC_nCC_nMC_nCA_xMA_nDD_)\
	F(xDC_nCC_nMC_nCA_xMA_nDD_)\
	F(oDC_xCC_nMC_nCA_xMA_nDD_)\
	F(nDC_xCC_nMC_nCA_xMA_nDD_)\
	F(xDC_xCC_nMC_nCA_xMA_nDD_)\
	F(oDC_oCC_xMC_nCA_xMA_nDD_)\
	F(nDC_oCC_xMC_nCA_xMA_nDD_)\
	F(xDC_oCC_xMC_nCA_xMA_nDD_)\
	F(oDC_nCC_xMC_nCA_xMA_nDD_)\
	F(nDC_nCC_xMC_nCA_xMA_nDD_)\
	F(xDC_nCC_xMC_nCA_xMA_nDD_)\
	F(oDC_xCC_xMC_nCA_xMA_nDD_)\
	F(nDC_xCC_xMC_nCA_xMA_nDD_)\
	F(xDC_xCC_xMC_nCA_xMA_nDD_)\
	F(oDC_oCC_oMC_xCA_xMA_nDD_)\
	F(nDC_oCC_oMC_xCA_xMA_nDD_)\
	F(xDC_oCC_oMC_xCA_xMA_nDD_)\
	F(oDC_nCC_oMC_xCA_xMA_nDD_)\
	F(nDC_nCC_oMC_xCA_xMA_nDD_)\
	F(xDC_nCC_oMC_xCA_xMA_nDD_)\
	F(oDC_xCC_oMC_xCA_xMA_nDD_)\
	F(nDC_xCC_oMC_xCA_xMA_nDD_)\
	F(xDC_xCC_oMC_xCA_xMA_nDD_)\
	F(oDC_oCC_nMC_xCA_xMA_nDD_)\
	F(nDC_oCC_nMC_xCA_xMA_nDD_)\
	F(xDC_oCC_nMC_xCA_xMA_nDD_)\
	F(oDC_nCC_nMC_xCA_xMA_nDD_)\
	F(nDC_nCC_nMC_xCA_xMA_nDD_)\
	F(xDC_nCC_nMC_xCA_xMA_nDD_)\
	F(oDC_xCC_nMC_xCA_xMA_nDD_)\
	F(nDC_xCC_nMC_xCA_xMA_nDD_)\
	F(xDC_xCC_nMC_xCA_xMA_nDD_)\
	F(oDC_oCC_xMC_xCA_xMA_nDD_)\
	F(nDC_oCC_xMC_xCA_xMA_nDD_)\
	F(xDC_oCC_xMC_xCA_xMA_nDD_)\
	F(oDC_nCC_xMC_xCA_xMA_nDD_)\
	F(nDC_nCC_xMC_xCA_xMA_nDD_)\
	F(xDC_nCC_xMC_xCA_xMA_nDD_)\
	F(oDC_xCC_xMC_xCA_xMA_nDD_)\
	F(nDC_xCC_xMC_xCA_xMA_nDD_)\
	F(xDC_xCC_xMC_xCA_xMA_nDD_)\
	F(oDC_oCC_oMC_oCA_oMA_xDD_)\
	F(nDC_oCC_oMC_oCA_oMA_xDD_)\
	F(xDC_oCC_oMC_oCA_oMA_xDD_)\
	F(oDC_nCC_oMC_oCA_oMA_xDD_)\
	F(nDC_nCC_oMC_oCA_oMA_xDD_)\
	F(xDC_nCC_oMC_oCA_oMA_xDD_)\
	F(oDC_xCC_oMC_oCA_oMA_xDD_)\
	F(nDC_xCC_oMC_oCA_oMA_xDD_)\
	F(xDC_xCC_oMC_oCA_oMA_xDD_)\
	F(oDC_oCC_nMC_oCA_oMA_xDD_)\
	F(nDC_oCC_nMC_oCA_oMA_xDD_)\
	F(xDC_oCC_nMC_oCA_oMA_xDD_)\
	F(oDC_nCC_nMC_oCA_oMA_xDD_)\
	F(nDC_nCC_nMC_oCA_oMA_xDD_)\
	F(xDC_nCC_nMC_oCA_oMA_xDD_)\
	F(oDC_xCC_nMC_oCA_oMA_xDD_)\
	F(nDC_xCC_nMC_oCA_oMA_xDD_)\
	F(xDC_xCC_nMC_oCA_oMA_xDD_)\
	F(oDC_oCC_xMC_oCA_oMA_xDD_)\
	F(nDC_oCC_xMC_oCA_oMA_xDD_)\
	F(xDC_oCC_xMC_oCA_oMA_xDD_)\
	F(oDC_nCC_xMC_oCA_oMA_xDD_)\
	F(nDC_nCC_xMC_oCA_oMA_xDD_)\
	F(xDC_nCC_xMC_oCA_oMA_xDD_)\
	F(oDC_xCC_xMC_oCA_oMA_xDD_)\
	F(nDC_xCC_xMC_oCA_oMA_xDD_)\
	F(xDC_xCC_xMC_oCA_oMA_xDD_)\
	F(oDC_oCC_oMC_nCA_oMA_xDD_)\
	F(nDC_oCC_oMC_nCA_oMA_xDD_)\
	F(xDC_oCC_oMC_nCA_oMA_xDD_)\
	F(oDC_nCC_oMC_nCA_oMA_xDD_)\
	F(nDC_nCC_oMC_nCA_oMA_xDD_)\
	F(xDC_nCC_oMC_nCA_oMA_xDD_)\
	F(oDC_xCC_oMC_nCA_oMA_xDD_)\
	F(nDC_xCC_oMC_nCA_oMA_xDD_)\
	F(xDC_xCC_oMC_nCA_oMA_xDD_)\
	F(oDC_oCC_nMC_nCA_oMA_xDD_)\
	F(nDC_oCC_nMC_nCA_oMA_xDD_)\
	F(xDC_oCC_nMC_nCA_oMA_xDD_)\
	F(oDC_nCC_nMC_nCA_oMA_xDD_)\
	F(nDC_nCC_nMC_nCA_oMA_xDD_)\
	F(xDC_nCC_nMC_nCA_oMA_xDD_)\
	F(oDC_xCC_nMC_nCA_oMA_xDD_)\
	F(nDC_xCC_nMC_nCA_oMA_xDD_)\
	F(xDC_xCC_nMC_nCA_oMA_xDD_)\
	F(oDC_oCC_xMC_nCA_oMA_xDD_)\
	F(nDC_oCC_xMC_nCA_oMA_xDD_)\
	F(xDC_oCC_xMC_nCA_oMA_xDD_)\
	F(oDC_nCC_xMC_nCA_oMA_xDD_)\
	F(nDC_nCC_xMC_nCA_oMA_xDD_)\
	F(xDC_nCC_xMC_nCA_oMA_xDD_)\
	F(oDC_xCC_xMC_nCA_oMA_xDD_)\
	F(nDC_xCC_xMC_nCA_oMA_xDD_)\
	F(xDC_xCC_xMC_nCA_oMA_xDD_)\
	F(oDC_oCC_oMC_xCA_oMA_xDD_)\
	F(nDC_oCC_oMC_xCA_oMA_xDD_)\
	F(xDC_oCC_oMC_xCA_oMA_xDD_)\
	F(oDC_nCC_oMC_xCA_oMA_xDD_)\
	F(nDC_nCC_oMC_xCA_oMA_xDD_)\
	F(xDC_nCC_oMC_xCA_oMA_xDD_)\
	F(oDC_xCC_oMC_xCA_oMA_xDD_)\
	F(nDC_xCC_oMC_xCA_oMA_xDD_)\
	F(xDC_xCC_oMC_xCA_oMA_xDD_)\
	F(oDC_oCC_nMC_xCA_oMA_xDD_)\
	F(nDC_oCC_nMC_xCA_oMA_xDD_)\
	F(xDC_oCC_nMC_xCA_oMA_xDD_)\
	F(oDC_nCC_nMC_xCA_oMA_xDD_)\
	F(nDC_nCC_nMC_xCA_oMA_xDD_)\
	F(xDC_nCC_nMC_xCA_oMA_xDD_)\
	F(oDC_xCC_nMC_xCA_oMA_xDD_)\
	F(nDC_xCC_nMC_xCA_oMA_xDD_)\
	F(xDC_xCC_nMC_xCA_oMA_xDD_)\
	F(oDC_oCC_xMC_xCA_oMA_xDD_)\
	F(nDC_oCC_xMC_xCA_oMA_xDD_)\
	F(xDC_oCC_xMC_xCA_oMA_xDD_)\
	F(oDC_nCC_xMC_xCA_oMA_xDD_)\
	F(nDC_nCC_xMC_xCA_oMA_xDD_)\
	F(xDC_nCC_xMC_xCA_oMA_xDD_)\
	F(oDC_xCC_xMC_xCA_oMA_xDD_)\
	F(nDC_xCC_xMC_xCA_oMA_xDD_)\
	F(xDC_xCC_xMC_xCA_oMA_xDD_)\
	F(oDC_oCC_oMC_oCA_nMA_xDD_)\
	F(nDC_oCC_oMC_oCA_nMA_xDD_)\
	F(xDC_oCC_oMC_oCA_nMA_xDD_)\
	F(oDC_nCC_oMC_oCA_nMA_xDD_)\
	F(nDC_nCC_oMC_oCA_nMA_xDD_)\
	F(xDC_nCC_oMC_oCA_nMA_xDD_)\
	F(oDC_xCC_oMC_oCA_nMA_xDD_)\
	F(nDC_xCC_oMC_oCA_nMA_xDD_)\
	F(xDC_xCC_oMC_oCA_nMA_xDD_)\
	F(oDC_oCC_nMC_oCA_nMA_xDD_)\
	F(nDC_oCC_nMC_oCA_nMA_xDD_)\
	F(xDC_oCC_nMC_oCA_nMA_xDD_)\
	F(oDC_nCC_nMC_oCA_nMA_xDD_)\
	F(nDC_nCC_nMC_oCA_nMA_xDD_)\
	F(xDC_nCC_nMC_oCA_nMA_xDD_)\
	F(oDC_xCC_nMC_oCA_nMA_xDD_)\
	F(nDC_xCC_nMC_oCA_nMA_xDD_)\
	F(xDC_xCC_nMC_oCA_nMA_xDD_)\
	F(oDC_oCC_xMC_oCA_nMA_xDD_)\
	F(nDC_oCC_xMC_oCA_nMA_xDD_)\
	F(xDC_oCC_xMC_oCA_nMA_xDD_)\
	F(oDC_nCC_xMC_oCA_nMA_xDD_)\
	F(nDC_nCC_xMC_oCA_nMA_xDD_)\
	F(xDC_nCC_xMC_oCA_nMA_xDD_)\
	F(oDC_xCC_xMC_oCA_nMA_xDD_)\
	F(nDC_xCC_xMC_oCA_nMA_xDD_)\
	F(xDC_xCC_xMC_oCA_nMA_xDD_)\
	F(oDC_oCC_oMC_nCA_nMA_xDD_)\
	F(nDC_oCC_oMC_nCA_nMA_xDD_)\
	F(xDC_oCC_oMC_nCA_nMA_xDD_)\
	F(oDC_nCC_oMC_nCA_nMA_xDD_)\
	F(nDC_nCC_oMC_nCA_nMA_xDD_)\
	F(xDC_nCC_oMC_nCA_nMA_xDD_)\
	F(oDC_xCC_oMC_nCA_nMA_xDD_)\
	F(nDC_xCC_oMC_nCA_nMA_xDD_)\
	F(xDC_xCC_oMC_nCA_nMA_xDD_)\
	F(oDC_oCC_nMC_nCA_nMA_xDD_)\
	F(nDC_oCC_nMC_nCA_nMA_xDD_)\
	F(xDC_oCC_nMC_nCA_nMA_xDD_)\
	F(oDC_nCC_nMC_nCA_nMA_xDD_)\
	F(nDC_nCC_nMC_nCA_nMA_xDD_)\
	F(xDC_nCC_nMC_nCA_nMA_xDD_)\
	F(oDC_xCC_nMC_nCA_nMA_xDD_)\
	F(nDC_xCC_nMC_nCA_nMA_xDD_)\
	F(xDC_xCC_nMC_nCA_nMA_xDD_)\
	F(oDC_oCC_xMC_nCA_nMA_xDD_)\
	F(nDC_oCC_xMC_nCA_nMA_xDD_)\
	F(xDC_oCC_xMC_nCA_nMA_xDD_)\
	F(oDC_nCC_xMC_nCA_nMA_xDD_)\
	F(nDC_nCC_xMC_nCA_nMA_xDD_)\
	F(xDC_nCC_xMC_nCA_nMA_xDD_)\
	F(oDC_xCC_xMC_nCA_nMA_xDD_)\
	F(nDC_xCC_xMC_nCA_nMA_xDD_)\
	F(xDC_xCC_xMC_nCA_nMA_xDD_)\
	F(oDC_oCC_oMC_xCA_nMA_xDD_)\
	F(nDC_oCC_oMC_xCA_nMA_xDD_)\
	F(xDC_oCC_oMC_xCA_nMA_xDD_)\
	F(oDC_nCC_oMC_xCA_nMA_xDD_)\
	F(nDC_nCC_oMC_xCA_nMA_xDD_)\
	F(xDC_nCC_oMC_xCA_nMA_xDD_)\
	F(oDC_xCC_oMC_xCA_nMA_xDD_)\
	F(nDC_xCC_oMC_xCA_nMA_xDD_)\
	F(xDC_xCC_oMC_xCA_nMA_xDD_)\
	F(oDC_oCC_nMC_xCA_nMA_xDD_)\
	F(nDC_oCC_nMC_xCA_nMA_xDD_)\
	F(xDC_oCC_nMC_xCA_nMA_xDD_)\
	F(oDC_nCC_nMC_xCA_nMA_xDD_)\
	F(nDC_nCC_nMC_xCA_nMA_xDD_)\
	F(xDC_nCC_nMC_xCA_nMA_xDD_)\
	F(oDC_xCC_nMC_xCA_nMA_xDD_)\
	F(nDC_xCC_nMC_xCA_nMA_xDD_)\
	F(xDC_xCC_nMC_xCA_nMA_xDD_)\
	F(oDC_oCC_xMC_xCA_nMA_xDD_)\
	F(nDC_oCC_xMC_xCA_nMA_xDD_)\
	F(xDC_oCC_xMC_xCA_nMA_xDD_)\
	F(oDC_nCC_xMC_xCA_nMA_xDD_)\
	F(nDC_nCC_xMC_xCA_nMA_xDD_)\
	F(xDC_nCC_xMC_xCA_nMA_xDD_)\
	F(oDC_xCC_xMC_xCA_nMA_xDD_)\
	F(nDC_xCC_xMC_xCA_nMA_xDD_)\
	F(xDC_xCC_xMC_xCA_nMA_xDD_)\
	F(oDC_oCC_oMC_oCA_xMA_xDD_)\
	F(nDC_oCC_oMC_oCA_xMA_xDD_)\
	F(xDC_oCC_oMC_oCA_xMA_xDD_)\
	F(oDC_nCC_oMC_oCA_xMA_xDD_)\
	F(nDC_nCC_oMC_oCA_xMA_xDD_)\
	F(xDC_nCC_oMC_oCA_xMA_xDD_)\
	F(oDC_xCC_oMC_oCA_xMA_xDD_)\
	F(nDC_xCC_oMC_oCA_xMA_xDD_)\
	F(xDC_xCC_oMC_oCA_xMA_xDD_)\
	F(oDC_oCC_nMC_oCA_xMA_xDD_)\
	F(nDC_oCC_nMC_oCA_xMA_xDD_)\
	F(xDC_oCC_nMC_oCA_xMA_xDD_)\
	F(oDC_nCC_nMC_oCA_xMA_xDD_)\
	F(nDC_nCC_nMC_oCA_xMA_xDD_)\
	F(xDC_nCC_nMC_oCA_xMA_xDD_)\
	F(oDC_xCC_nMC_oCA_xMA_xDD_)\
	F(nDC_xCC_nMC_oCA_xMA_xDD_)\
	F(xDC_xCC_nMC_oCA_xMA_xDD_)\
	F(oDC_oCC_xMC_oCA_xMA_xDD_)\
	F(nDC_oCC_xMC_oCA_xMA_xDD_)\
	F(xDC_oCC_xMC_oCA_xMA_xDD_)\
	F(oDC_nCC_xMC_oCA_xMA_xDD_)\
	F(nDC_nCC_xMC_oCA_xMA_xDD_)\
	F(xDC_nCC_xMC_oCA_xMA_xDD_)\
	F(oDC_xCC_xMC_oCA_xMA_xDD_)\
	F(nDC_xCC_xMC_oCA_xMA_xDD_)\
	F(xDC_xCC_xMC_oCA_xMA_xDD_)\
	F(oDC_oCC_oMC_nCA_xMA_xDD_)\
	F(nDC_oCC_oMC_nCA_xMA_xDD_)\
	F(xDC_oCC_oMC_nCA_xMA_xDD_)\
	F(oDC_nCC_oMC_nCA_xMA_xDD_)\
	F(nDC_nCC_oMC_nCA_xMA_xDD_)\
	F(xDC_nCC_oMC_nCA_xMA_xDD_)\
	F(oDC_xCC_oMC_nCA_xMA_xDD_)\
	F(nDC_xCC_oMC_nCA_xMA_xDD_)\
	F(xDC_xCC_oMC_nCA_xMA_xDD_)\
	F(oDC_oCC_nMC_nCA_xMA_xDD_)\
	F(nDC_oCC_nMC_nCA_xMA_xDD_)\
	F(xDC_oCC_nMC_nCA_xMA_xDD_)\
	F(oDC_nCC_nMC_nCA_xMA_xDD_)\
	F(nDC_nCC_nMC_nCA_xMA_xDD_)\
	F(xDC_nCC_nMC_nCA_xMA_xDD_)\
	F(oDC_xCC_nMC_nCA_xMA_xDD_)\
	F(nDC_xCC_nMC_nCA_xMA_xDD_)\
	F(xDC_xCC_nMC_nCA_xMA_xDD_)\
	F(oDC_oCC_xMC_nCA_xMA_xDD_)\
	F(nDC_oCC_xMC_nCA_xMA_xDD_)\
	F(xDC_oCC_xMC_nCA_xMA_xDD_)\
	F(oDC_nCC_xMC_nCA_xMA_xDD_)\
	F(nDC_nCC_xMC_nCA_xMA_xDD_)\
	F(xDC_nCC_xMC_nCA_xMA_xDD_)\
	F(oDC_xCC_xMC_nCA_xMA_xDD_)\
	F(nDC_xCC_xMC_nCA_xMA_xDD_)\
	F(xDC_xCC_xMC_nCA_xMA_xDD_)\
	F(oDC_oCC_oMC_xCA_xMA_xDD_)\
	F(nDC_oCC_oMC_xCA_xMA_xDD_)\
	F(xDC_oCC_oMC_xCA_xMA_xDD_)\
	F(oDC_nCC_oMC_xCA_xMA_xDD_)\
	F(nDC_nCC_oMC_xCA_xMA_xDD_)\
	F(xDC_nCC_oMC_xCA_xMA_xDD_)\
	F(oDC_xCC_oMC_xCA_xMA_xDD_)\
	F(nDC_xCC_oMC_xCA_xMA_xDD_)\
	F(xDC_xCC_oMC_xCA_xMA_xDD_)\
	F(oDC_oCC_nMC_xCA_xMA_xDD_)\
	F(nDC_oCC_nMC_xCA_xMA_xDD_)\
	F(xDC_oCC_nMC_xCA_xMA_xDD_)\
	F(oDC_nCC_nMC_xCA_xMA_xDD_)\
	F(nDC_nCC_nMC_xCA_xMA_xDD_)\
	F(xDC_nCC_nMC_xCA_xMA_xDD_)\
	F(oDC_xCC_nMC_xCA_xMA_xDD_)\
	F(nDC_xCC_nMC_xCA_xMA_xDD_)\
	F(xDC_xCC_nMC_xCA_xMA_xDD_)\
	F(oDC_oCC_xMC_xCA_xMA_xDD_)\
	F(nDC_oCC_xMC_xCA_xMA_xDD_)\
	F(xDC_oCC_xMC_xCA_xMA_xDD_)\
	F(oDC_nCC_xMC_xCA_xMA_xDD_)\
	F(nDC_nCC_xMC_xCA_xMA_xDD_)\
	F(xDC_nCC_xMC_xCA_xMA_xDD_)\
	F(oDC_xCC_xMC_xCA_xMA_xDD_)\
	F(nDC_xCC_xMC_xCA_xMA_xDD_)\
	F(xDC_xCC_xMC_xCA_xMA_xDD_)\

